name: Make release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out to the repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make data
      run: |
        python make_df.py
        ls -lah
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: 'latest'
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.csv.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}